apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ckan.fullname" . }}-redis

spec:
  accessModes:
    - ReadWriteOnce

  {{- if .Values.redis.storage.storageClass }}
  storageClassName: {{ .Values.redis.storage.storageClass | quote }}
  {{- end }}

  resources:
    requests:
      storage: {{ .Values.redis.storage.size }}