apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ckan.fullname" . }}-secret
type: Opaque

stringData:
  CKAN_SYSADMIN_NAME: {{ .Values.ckan.sysadmin.name | quote }}
  CKAN_SYSADMIN_PASSWORD: {{ .Values.ckan.sysadmin.password | quote }}
  CKAN_SYSADMIN_EMAIL: {{ .Values.ckan.sysadmin.email | quote }}

  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}

  DATASTORE_READONLY_USER: {{ .Values.postgres.datastore.user | quote }}
  DATASTORE_READONLY_PASSWORD: {{ .Values.postgres.datastore.password | quote }}