{{- if .Values.solr.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ckan.fullname" . }}-solr

spec:
  replicas: 1

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ckan.fullname" . }}-solr

  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ckan.fullname" . }}-solr

    spec:
      containers:
        - name: solr

          image: "{{ .Values.solr.image.repository }}:{{ .Values.solr.image.tag }}"
          imagePullPolicy: {{ .Values.solr.image.pullPolicy }}

          ports:
            - name: solr
              containerPort: 8983

          resources:
{{ toYaml .Values.solr.resources | indent 12 }}

          {{- if .Values.solr.storage.enabled }}
          volumeMounts:
            - name: solr-data
              mountPath: /var/solr
          {{- end }}

      {{- if .Values.solr.storage.enabled }}
      volumes:
        - name: solr-data
          persistentVolumeClaim:
            claimName: {{ include "ckan.fullname" . }}-solr
      {{- end }}
{{- end }}