{{- if and .Values.solr.enabled .Values.solr.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ckan.fullname" . }}-solr

spec:
  accessModes:
    - ReadWriteOnce

  {{- if .Values.solr.storage.storageClass }}
  storageClassName: {{ .Values.solr.storage.storageClass | quote }}
  {{- end }}

  resources:
    requests:
      storage: {{ .Values.solr.storage.size }}
{{- end }}